services:
  db:
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: monlap-backend
    build:
      context: ./backend
      dockerfile: go.dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./backend/uploads:/root/uploads
    env_file:
      - ./backend/.env

volumes:
  pgdata: {}